// test_protocol.cpp — golden-vector conformance for the C++ KVB1 codec.
//
// Go, Python, and C++ must agree byte-for-byte. Two golden families are
// pinned here:
//
//   1. The frozen repo goldens (internal/protocol/testdata/frames/*.hex —
//      PROTOCOL.md §11/§12 worked examples A/B), loaded from
//      $KVB_GOLDEN_DIR when set, else from embedded copies (the wheel/sdist
//      pattern the Python tests use; embeds are transcribed from the repo
//      files, never by hand).
//   2. Frames generated by the Python reference codec (python/kvblockd
//      protocol.py) for the verbs the repo goldens don't cover — HELLO
//      request, PUT BEGIN, BATCH_GET request — stored in test/golden/ and
//      embedded here. The C++ encoder must reproduce them from scratch.
//
// Plus the two §12 payload-checksum pins that anchor xxh3 parity, and the
// canonical CRC32C check value.
//
// No test framework: a tiny CHECK macro, exit code = failure count, every
// failure names the vector. Runs in milliseconds.

#include "kvblockd_client.h"

#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>
#include <vector>

using namespace kvb;

static int g_failures = 0;

#define CHECK(cond, ...)                                                                        \
    do {                                                                                        \
        if (!(cond)) {                                                                          \
            g_failures++;                                                                       \
            std::printf("FAIL %s:%d: ", __FILE__, __LINE__);                                    \
            std::printf(__VA_ARGS__);                                                           \
            std::printf("\n");                                                                  \
        }                                                                                       \
    } while (0)

// --- golden loading -----------------------------------------------------------

static std::vector<uint8_t> unhex(const std::string &s) {
    std::vector<uint8_t> out;
    out.reserve(s.size() / 2);
    auto nib = [](char c) -> int {
        if (c >= '0' && c <= '9') return c - '0';
        if (c >= 'a' && c <= 'f') return c - 'a' + 10;
        if (c >= 'A' && c <= 'F') return c - 'A' + 10;
        return -1;
    };
    for (size_t i = 0; i + 1 < s.size(); i += 2) {
        int hi = nib(s[i]), lo = nib(s[i + 1]);
        if (hi < 0 || lo < 0) break; // stop at whitespace/newline
        out.push_back(static_cast<uint8_t>(hi << 4 | lo));
    }
    return out;
}

// Embedded copies of the frozen repo goldens (transcribed from
// internal/protocol/testdata/frames/*.hex).
static const char *kExampleARequest =
    "4b5642310102000007000000000000000110000000000000000000000000000000000000"
    "000000000000000000000000000000000000000068000000ffa72e5f0300000000000000"
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbb"
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccc"
    "cccccccccccccccccccccccccccccccccccccccccccccccc";
static const char *kExampleAResponse =
    "4b5642310102010007000000000010000110000000000000000000000000000000000000"
    "000000000000000000000000000000000000000018000000232e93d60000000003000000"
    "02000000000000000000100000000000";
static const char *kExampleBResponseHeader =
    "4b5642310103010007000000000010000210000000000000000000000000000000000000"
    "000000000000000000000000000000000000000040003800b99d4fc50000000003000000"
    "000000000300000000000000000010004ffc818960eb7dc400000000000028005dc466ba"
    "22169ed610000000000000000000000000000000";

// Frames generated by the Python reference codec (see test/golden/*.hex).
static const char *kHelloRequest =
    "4b5642310101000000000000000000000100000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000380000009c97150b0101000002000000"
    "0000000000000000000000000000000000000000060001000d00000073656b726574746b"
    "76626c6f636b642d6e69786c";
static const char *kPutBeginFrame =
    "4b5642310104000007000000000000000120000000000000dddddddddddddddddddddddd"
    "dddddddddddddddddddddddddddddddddddddddd180000006843c97b0000280000000000"
    "5dc466ba22169ed60000000000000000";
static const char *kBatchGetRequest =
    "4b5642310103000007000000000000000210000000000000000000000000000000000000"
    "00000000000000000000000000000000000000006800000062482e250300000000000000"
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbb"
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccc"
    "cccccccccccccccccccccccccccccccccccccccccccccccc";

// Repo goldens resolve via $KVB_GOLDEN_DIR (internal/protocol/testdata/frames);
// the Python-generated adapter goldens via $KVB_ADAPTER_GOLDEN_DIR
// (adapters/nixl/test/golden). Either way the embedded copy is the fallback.
static std::vector<uint8_t> load_golden_env(const char *env, const char *name,
                                            const char *embedded) {
    const char *dir = std::getenv(env);
    if (dir != nullptr) {
        std::ifstream f(std::string(dir) + "/" + name + ".hex");
        if (f) {
            std::string hex((std::istreambuf_iterator<char>(f)),
                            std::istreambuf_iterator<char>());
            std::vector<uint8_t> v = unhex(hex);
            if (!v.empty()) return v;
        }
        std::printf("WARN: could not read %s from %s=%s, using embedded\n", name, env, dir);
    }
    return unhex(embedded);
}

static std::vector<uint8_t> load_golden(const char *name, const char *embedded) {
    return load_golden_env("KVB_GOLDEN_DIR", name, embedded);
}

static std::vector<uint8_t> load_adapter_golden(const char *name, const char *embedded) {
    return load_golden_env("KVB_ADAPTER_GOLDEN_DIR", name, embedded);
}

static Key fill_key(uint8_t b) {
    Key k;
    k.fill(b);
    return k;
}

// --- tests ----------------------------------------------------------------------

static void test_crc32c_check_value() {
    // The canonical CRC32C check value (RFC 3720 appendix / Castagnoli).
    const char *digits = "123456789";
    CHECK(crc32c(reinterpret_cast<const uint8_t *>(digits), 9) == 0xE3069283u,
          "crc32c(\"123456789\") != 0xE3069283");
}

static void test_repo_golden_crc_pins() {
    struct {
        const char *name;
        const char *embedded;
        uint32_t want;
    } cases[] = {
        {"example-a-request", kExampleARequest, 0x5F2EA7FFu},
        {"example-a-response", kExampleAResponse, 0xD6932E23u},
        {"example-b-response-header", kExampleBResponseHeader, 0xC54F9DB9u},
    };
    for (const auto &c : cases) {
        std::vector<uint8_t> frame = load_golden(c.name, c.embedded);
        CHECK(frame.size() >= kHeaderSize, "%s: too short", c.name);
        if (frame.size() < kHeaderSize) continue;
        CHECK(crc32c(frame.data(), 60) == c.want, "%s: computed CRC != PROTOCOL.md pin", c.name);
        CHECK(get_u32(frame.data() + 60) == c.want, "%s: stored CRC != PROTOCOL.md pin", c.name);
    }
}

static void test_example_a_request_parse_and_reencode() {
    std::vector<uint8_t> frame = load_golden("example-a-request", kExampleARequest);
    Header h;
    std::string err;
    CHECK(Header::parse(frame.data(), h, err), "example-a-request: parse failed: %s",
          err.c_str());
    CHECK(h.opcode == Op::BatchExists, "opcode != BATCH_EXISTS");
    CHECK(h.flags == 0, "flags != 0");
    CHECK(h.namespace_id == 7, "namespace_id != 7");
    CHECK(h.credit == 0, "credit != 0 on a request");
    CHECK(h.request_id == 0x1001, "request_id != 0x1001");
    CHECK(h.payload_len == 0x68, "payload_len != 104");

    // Header re-marshal must be byte-identical (decode->encode parity).
    uint8_t out[kHeaderSize];
    h.marshal_to(out);
    CHECK(std::memcmp(out, frame.data(), kHeaderSize) == 0,
          "example-a-request: re-marshaled header differs");

    // Full-frame encode from scratch (the §11 worked example).
    std::vector<uint8_t> body;
    append_keylist(body, 0, {fill_key(0xAA), fill_key(0xBB), fill_key(0xCC)});
    Header h2;
    h2.opcode = Op::BatchExists;
    h2.namespace_id = 7;
    h2.request_id = 0x1001;
    h2.payload_len = static_cast<uint32_t>(body.size());
    uint8_t hdr2[kHeaderSize];
    h2.marshal_to(hdr2);
    CHECK(std::memcmp(hdr2, frame.data(), kHeaderSize) == 0,
          "example-a-request: from-scratch header differs");
    CHECK(body.size() == frame.size() - kHeaderSize &&
              std::memcmp(body.data(), frame.data() + kHeaderSize, body.size()) == 0,
          "example-a-request: from-scratch body differs");
}

static void test_example_a_response_fields() {
    std::vector<uint8_t> frame = load_golden("example-a-response", kExampleAResponse);
    Header h;
    std::string err;
    CHECK(Header::parse(frame.data(), h, err), "example-a-response: parse failed: %s",
          err.c_str());
    CHECK((h.flags & kFlagResp) != 0, "F_RESP not set");
    CHECK(h.credit == 0x00100000, "piggybacked credit grant != 1 MiB");
    Preamble p;
    CHECK(parse_preamble(frame.data() + kHeaderSize, frame.size() - kHeaderSize, p),
          "preamble parse failed");
    CHECK(p.status == Status::OK && p.count == 3, "preamble != (OK, 3)");
    uint32_t n_consec = get_u32(frame.data() + kHeaderSize + kPreambleSize);
    CHECK(n_consec == 2, "n_consecutive != 2 (hit, hit, miss)");
    // Bitmap: K0=OK, K1=OK, K2=NOT_FOUND, then 5 pad bytes.
    const uint8_t *bm = frame.data() + kHeaderSize + kPreambleSize + 8;
    CHECK(bm[0] == 0x00 && bm[1] == 0x00 && bm[2] == 0x10, "per-key bitmap mismatch");
}

static void test_example_b_response_descriptors() {
    std::vector<uint8_t> frame = load_golden("example-b-response-header", kExampleBResponseHeader);
    Header h;
    std::string err;
    CHECK(Header::parse(frame.data(), h, err), "example-b: parse failed: %s", err.c_str());
    CHECK(h.opcode == Op::BatchGet && (h.flags & kFlagResp), "not a GET response");
    CHECK((h.flags & kFlagMore) == 0, "single-frame response must not set F_MORE");
    CHECK(h.request_id == 0x1002, "request_id != 0x1002");
    CHECK(h.payload_len == 0x00380040, "payload_len != 3,670,080");

    // Re-marshal parity for the response header too.
    uint8_t out[kHeaderSize];
    h.marshal_to(out);
    CHECK(std::memcmp(out, frame.data(), kHeaderSize) == 0, "example-b: re-marshal differs");

    const uint8_t *body = frame.data() + kHeaderSize;
    size_t blen = frame.size() - kHeaderSize;
    Preamble p;
    CHECK(parse_preamble(body, blen, p) && p.status == Status::OK && p.count == 3,
          "example-b preamble != (OK, 3)");
    CHECK(get_u32(body + 8) == 0 && get_u32(body + 12) == 3, "first_index/total_keys mismatch");
    Desc d0, d1, d2;
    CHECK(parse_desc(body + 16, blen - 16, d0), "desc0 parse");
    CHECK(parse_desc(body + 32, blen - 32, d1), "desc1 parse");
    CHECK(parse_desc(body + 48, blen - 48, d2), "desc2 parse");
    CHECK(d0.status == Status::OK && d0.len == 1048576 && d0.xxh3 == 0xC47DEB608981FC4Full,
          "desc0 != (OK, 1 MiB, pinned xxh3)");
    CHECK(d1.status == Status::OK && d1.len == 2621440 && d1.xxh3 == 0xD69E1622BA66C45Dull,
          "desc1 != (OK, 2.5 MB, pinned xxh3)");
    CHECK(d2.status == Status::NotFound && d2.len == 0 && d2.xxh3 == 0,
          "desc2 != (NOT_FOUND, 0, 0)");
}

static void test_python_parity_hello() {
    // Generated by python kvblockd.protocol: pack_hello_req(FEAT_EXISTS_BITMAP,
    // 0, 0, b"sekret", b"t", b"kvblockd-nixl") under Header(HELLO, rid=1).
    std::vector<uint8_t> want = load_adapter_golden("hello-request", kHelloRequest);
    std::vector<uint8_t> body;
    append_hello_req(body, kFeatExistsBitmap, 0, 0, "sekret", "t", "kvblockd-nixl");
    Header h;
    h.opcode = Op::Hello;
    h.request_id = 1;
    h.payload_len = static_cast<uint32_t>(body.size());
    uint8_t hdr[kHeaderSize];
    h.marshal_to(hdr);
    CHECK(want.size() == kHeaderSize + body.size(), "HELLO: frame length differs (%zu vs %zu)",
          want.size(), kHeaderSize + body.size());
    CHECK(std::memcmp(hdr, want.data(), kHeaderSize) == 0, "HELLO: header differs from Python");
    CHECK(std::memcmp(body.data(), want.data() + kHeaderSize, body.size()) == 0,
          "HELLO: body differs from Python");
}

static void test_python_parity_put_begin() {
    // Python: pack_put_begin(2621440, 0, 0xD69E1622BA66C45D) under
    // Header(PUT_STREAM, subop BEGIN, ns=7, rid=0x2001, key=dd*32).
    std::vector<uint8_t> want = load_adapter_golden("put-begin", kPutBeginFrame);
    std::vector<uint8_t> body;
    append_put_begin(body, 2621440, 0, 0xD69E1622BA66C45Dull);
    Header h;
    h.opcode = Op::PutStream;
    h.flags = with_subop(0, kPutBegin);
    h.namespace_id = 7;
    h.request_id = 0x2001;
    h.key = fill_key(0xDD);
    h.payload_len = static_cast<uint32_t>(body.size());
    uint8_t hdr[kHeaderSize];
    h.marshal_to(hdr);
    CHECK(want.size() == kHeaderSize + body.size(), "BEGIN: frame length differs");
    CHECK(std::memcmp(hdr, want.data(), kHeaderSize) == 0, "BEGIN: header differs from Python");
    CHECK(std::memcmp(body.data(), want.data() + kHeaderSize, body.size()) == 0,
          "BEGIN: body differs from Python");
}

static void test_python_parity_batch_get_request() {
    // The §12 example-B request: same shape as A, opcode 03, rid 0x1002.
    std::vector<uint8_t> want = load_adapter_golden("batch-get-request", kBatchGetRequest);
    std::vector<uint8_t> body;
    append_keylist(body, 0, {fill_key(0xAA), fill_key(0xBB), fill_key(0xCC)});
    Header h;
    h.opcode = Op::BatchGet;
    h.namespace_id = 7;
    h.request_id = 0x1002;
    h.payload_len = static_cast<uint32_t>(body.size());
    uint8_t hdr[kHeaderSize];
    h.marshal_to(hdr);
    CHECK(want.size() == kHeaderSize + body.size(), "GETREQ: frame length differs");
    CHECK(std::memcmp(hdr, want.data(), kHeaderSize) == 0, "GETREQ: header differs from Python");
    CHECK(std::memcmp(body.data(), want.data() + kHeaderSize, body.size()) == 0,
          "GETREQ: body differs from Python");
}

static void test_xxh3_payload_pins() {
    // §12 golden payload convention: K0 = 1 MiB of 0xAA, K1 = 2.5 MB of 0xBB.
    std::vector<uint8_t> k0(1048576, 0xAA), k1(2621440, 0xBB);
    CHECK(xxh3_64(k0.data(), k0.size()) == 0xC47DEB608981FC4Full, "xxh3(K0) != pinned golden");
    CHECK(xxh3_64(k1.data(), k1.size()) == 0xD69E1622BA66C45Dull, "xxh3(K1) != pinned golden");
}

static void test_bad_frames_rejected() {
    std::vector<uint8_t> frame = load_golden("example-a-request", kExampleARequest);
    Header h;
    std::string err;
    std::vector<uint8_t> bad = frame;
    bad[0] ^= 0xFF; // magic
    CHECK(!Header::parse(bad.data(), h, err), "corrupt magic accepted");
    bad = frame;
    bad[4] = 0x02; // version
    CHECK(!Header::parse(bad.data(), h, err), "unknown version accepted");
    bad = frame;
    bad[60] ^= 0xFF; // stored CRC
    CHECK(!Header::parse(bad.data(), h, err), "corrupt CRC accepted");
    bad = frame;
    bad[57] ^= 0x01; // payload_len byte -> CRC must now mismatch
    CHECK(!Header::parse(bad.data(), h, err), "tampered payload_len accepted");
}

static void test_hello_resp_roundtrip() {
    // Self-consistency for the one decoder without a repo golden: build a §3.1
    // OK response body field-by-field at the documented offsets, then parse.
    std::vector<uint8_t> b;
    b.insert(b.end(), {0x00, 0, 0, 0, 0, 0, 0, 0}); // preamble OK, count=0
    b.push_back(0x01);                              // proto
    b.insert(b.end(), {0, 0, 0});
    for (int i = 0; i < 8; i++) b.push_back(i == 0 ? 0x03 : 0x00); // features = OOO|BITMAP
    auto push32 = [&](uint32_t v) {
        uint8_t tmp[4];
        put_u32(tmp, v);
        b.insert(b.end(), tmp, tmp + 4);
    };
    push32(512);        // max_batch_keys
    push32(256 << 20);  // max_frame_len
    push32(32 << 20);   // max_blob_len
    push32(7);          // namespace_id
    push32(128 << 20);  // initial_credit
    push32(5000);       // lease_default_ms
    push32(60000);      // lease_max_ms
    push32(30000);      // stream_timeout_ms
    b.insert(b.end(), {8, 0, 0, 0});                       // name_len=8, reserved
    const char *nm = "kvblockd";                           // 8 bytes
    b.insert(b.end(), nm, nm + 8);                         // fixed(56)+8 = 64, 8-aligned
    HelloResp r;
    CHECK(parse_hello_resp(b.data(), b.size(), r), "hello resp parse failed");
    CHECK(r.status == Status::OK && r.proto == 1, "hello resp status/proto");
    CHECK(r.features == (kFeatOOO | kFeatExistsBitmap), "hello resp features");
    CHECK(r.max_batch_keys == 512 && r.max_frame_len == (256u << 20) &&
              r.max_blob_len == (32u << 20),
          "hello resp limits");
    CHECK(r.namespace_id == 7 && r.initial_credit == (128u << 20), "hello resp ns/credit");
    CHECK(r.lease_default_ms == 5000 && r.lease_max_ms == 60000 && r.stream_timeout_ms == 30000,
          "hello resp lease/stream fields");
    CHECK(r.server_name == "kvblockd", "hello resp server_name");
}

int main() {
    test_crc32c_check_value();
    test_repo_golden_crc_pins();
    test_example_a_request_parse_and_reencode();
    test_example_a_response_fields();
    test_example_b_response_descriptors();
    test_python_parity_hello();
    test_python_parity_put_begin();
    test_python_parity_batch_get_request();
    test_xxh3_payload_pins();
    test_bad_frames_rejected();
    test_hello_resp_roundtrip();
    if (g_failures == 0) {
        std::printf("test_protocol: all golden-vector checks passed\n");
        return 0;
    }
    std::printf("test_protocol: %d FAILURE(S)\n", g_failures);
    return 1;
}
