package client

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// TestWireKeyGoldenParity asserts Go's WireKey matches the committed vectors
// generated by Python kvblockd.hashing.wire_key — the Go↔Python identity gate
// that keeps two clients (or a client and a connector) deriving the SAME wire
// key for the same CacheEngineKey.
func TestWireKeyGoldenParity(t *testing.T) {
	path := filepath.Join("..", "..", "python", "kvblockd", "tests", "golden", "hash_chain.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("golden vectors not present (%v)", err)
	}
	var doc struct {
		Scheme  string `json:"scheme"`
		Vectors []struct {
			Fields     []string `json:"fields"`
			WireKeyHex string   `json:"wire_key_hex"`
		} `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	if doc.Scheme != "kvblockd-cek-v1" {
		t.Fatalf("scheme = %q", doc.Scheme)
	}
	if len(doc.Vectors) == 0 {
		t.Fatal("no vectors")
	}
	for i, v := range doc.Vectors {
		got := WireKey(v.Fields...)
		if hex.EncodeToString(got[:]) != v.WireKeyHex {
			t.Fatalf("vector %d %v: got %x, want %s", i, v.Fields, got, v.WireKeyHex)
		}
	}
}

// TestWireKeyLengthPrefixed pins the anti-collision property: differently
// split field boundaries must not hash equal.
func TestWireKeyLengthPrefixed(t *testing.T) {
	a := WireKey("vllm", "org/model", "1", "0", "5")
	b := WireKey("vllm", "org", "model/1", "0", "5")
	if a == b {
		t.Fatal("length-prefixing failed: joined-ambiguous fields collided")
	}
}
